# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /posts/:title/
relative_permalinks: true

# Setup
title:               John Blog 
tagline:             'Personal Tips, Memos, LifeLogs' 
description:         'This is John Blog'
url:                 https://johnokaz.github.io/
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              John Okada
  url:               https://twitter.com/johnokaz
  email:             johnokaz@gmail.com

# Custom vars
version:             1.0.0

# Add
github:
  repo:  https://github.com/johnokaz/johnokaz.github.io.git

markdown: redcarpet
redcarpet:
  extensions: [tables,autolink,strikethrough]
